---
# tasks for omero_ms_image_region


- name: Check that the ms conf exists
  become: true
  ansible.builtin.stat:
     path: "{{ ms_folder }}/{{ ms_name }}"
  register: stat_result

- name: display stats
  debug:
    var: stat_result.stat.exists

- name: Use sha256 to calculate the checksum
  become: true
  ansible.builtin.stat:
    path: "{{ ms_folder }}/{{ ms_name }}"
    checksum_algorithm: sha256
  register: stat_ssh256

- name: display stats
  debug:
    var: stat_ssh256.stat.checksum

- import_tasks: pre_tasks.yml
  when:
   - stat_ssh256.stat.checksum is undefined or  omero_ms_sha256 !=  stat_ssh256.stat.checksum
   - not stat_result.stat.exists

- name: omero-ms-image-region | copy config file
  become: true
  become_user: "{{ ms_user }}"
  ansible.builtin.template:
    dest: "{{ ms_folder }}/omero-ms-image-region/conf/config.yaml"
    src: config.yaml.j2

- name: omero-ms-image-region | copy log config file
  become: true
  become_user: "{{ ms_user }}"
  ansible.builtin.template:
    dest: "{{ ms_folder }}/omero-ms-image-region/conf/logback.xml"
    src: logback.xml.j2

- name: omero-ms-image-region | copy run.sh
  become: true
  become_user: "{{ ms_user }}"
  ansible.builtin.template:
    dest: "{{ ms_folder }}/omero-ms-image-region/run.sh"
    src: run.sh.j2
    mode: +x

- name: omero-ms-image-region | copy stop.sh
  become: true
  become_user: "{{ ms_user }}"
  ansible.builtin.template:
    dest: "{{ ms_folder }}/omero-ms-image-region/stop.sh"
    src: stop.sh.j2
    mode: +x

- name: omero-ms-image-region | systemd service
  become: true
  ansible.builtin.template:
    dest: /etc/systemd/system/omero-ms-image-region.service
    src: omero-ms-image-region.service.j2
    mode: 0644
  notify:
    - enable omero-ms-image-region service
    - restart omero-ms-image-region service

- name: omero-ms-image-region | selinux http_port_t for ms port
  become: true
  ansible.builtin.seport:
    ports: "{{ ms_port }}"
    proto: tcp
    setype: http_port_t
    state: present
  notify:
    - restart omero-ms-image-region service
  when: ansible_facts.selinux.status == 'enabled'

- import_tasks: update_nginx_config.yml
  when: update_nginx
