---

- name: Converge
  hosts: all

  roles:
    - name: ome.postgresql
      postgresql_version: "15"
      postgresql_databases:
       - name: omero
      postgresql_users:
        - user: { { db_user_name } }
          password: { { db_password } }
          databases: [ db_name ]
    - name: ome.omero_server
      omero_server_release: 5.6.10
      omero_server_dbhost: postgres.example.org
      omero_server_dbuser: { { db_user_name } }
      omero_server_dbname: { { db_name } }
      omero_server_dbpassword: { { db_password } }
      omero_server_system_user: {{ ms_user }}
      postgresql_version: "15"
    - name: ome.omero_web
      omero_web_setup_redis_session: true
      omero_web_config_set:
         "omero.web.caches":
           "default":
             "BACKEND": "django_redis.cache.RedisCache"
             "LOCATION": "redis://127.0.0.1:6379/0"
         "omero.web.session_engine": "django.contrib.sessions.backends.cache"

    - role: ome.omero_ms_image_region
